<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/"  xmlns:isc="http://dtd.3dcart.com/ecommerce-1.0.dtd">
<channel>
<title><![CDATA[Sample Store: On Sale]]></title>
<link>https://techsave-preview-com.3dcartstores.com</link>
<pubDate>Sun, 16 Mar 2025 00:00:00 EST</pubDate>
<description><![CDATA[List of Items On Sale at Sample Store]]></description>
<language>en-us</language>
<isc:store_name><![CDATA[Sample Store]]></isc:store_name>
<item>
<title><![CDATA[15.6'' Laptop]]></title>
<link>https://techsave-preview-com.3dcartstores.com/156-Laptop_p_12.html</link>
<pubDate>Sun, 16 Mar 2025 00:00:00 EST</pubDate>
<description><![CDATA[ <p><a href="https://techsave-preview-com.3dcartstores.com/156-Laptop_p_12.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-laptop1_thumbnail.jpg" align="right" border=0></a>The new Aspire 3 Series is the perfect for every need. It packs a beautiful 15.6 HD screen, solid performance, and the latest WiFi into an attractive design that's easy to place in a backpack and take to class.7th Generation Intel Core i5-7200U Proce...<a href="https://techsave-preview-com.3dcartstores.com/156-Laptop_p_12.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $290.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=12&out=1" target="_new">Add to Cart</a>]</p><br clear=all> ]]></description>
<guid isPermaLink="false">https://techsave-preview-com.3dcartstores.com/156-Laptop_p_12.html</guid>
<content:encoded><![CDATA[<p><a href="https://techsave-preview-com.3dcartstores.com/156-Laptop_p_12.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-laptop1_thumbnail.jpg" align="right" border=0></a>The new Aspire 3 Series is the perfect for every need. It packs a beautiful 15.6 HD screen, solid performance, and the latest WiFi into an attractive design that's easy to place in a backpack and take to class.7th Generation Intel Core i5-7200U Proce...<a href="https://techsave-preview-com.3dcartstores.com/156-Laptop_p_12.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $290.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=12&out=1" target="_new">Add to Cart</a>]</p><br clear=all>]]></content:encoded>
<isc:description><![CDATA[<span style="font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">The new Aspire 3 Series is the perfect for every need. It packs a beautiful 15.6" HD screen, solid performance, and the latest WiFi into an attractive design that's easy to place in a backpack and take to class.</span><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">7th Generation Intel Core i5-7200U Processor (Up to 3.1GHz) <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">15.6" HD (1366 x 768) Widescreen LED-backlit Display <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">Intel HD Graphics 620 <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">6GB DDR4 Dual Channel Memory <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">1TB 5400RPM SATA Hard Drive <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">Windows 10 Home <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">2-cell Li-Ion (4810 mAh) Battery, Up to 6.5 Hours Battery Life <span style="box-sizing: border-box; white-space: pre;"> </span></div>  ]]></isc:description>
<isc:productid><![CDATA[15.6'' Laptop]]></isc:productid>
<isc:thumb><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-laptop1_thumbnail.jpg]]></isc:thumb>
<isc:image><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-laptop1.jpg]]></isc:image>
<isc:price><![CDATA[$500.00]]></isc:price>
</item>
<item>
<title><![CDATA[Game Controller]]></title>
<link>https://techsave-preview-com.3dcartstores.com/Game-Controller_p_13.html</link>
<pubDate>Sun, 16 Mar 2025 00:00:00 EST</pubDate>
<description><![CDATA[ <p><a href="https://techsave-preview-com.3dcartstores.com/Game-Controller_p_13.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-controller1_thumbnail.jpg" align="right" border=0></a>controller is compatible with PC Windows (Xp/7/8/10) or later versions, Android 4.0 and PS3 via wired connection, working great with Laptop/PC, Android smart phones, TV boxes, tablets and PS3. This game controller can identify all the deices automati...<a href="https://techsave-preview-com.3dcartstores.com/Game-Controller_p_13.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $45.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=13&out=1" target="_new">Add to Cart</a>]</p><br clear=all> ]]></description>
<guid isPermaLink="false">https://techsave-preview-com.3dcartstores.com/Game-Controller_p_13.html</guid>
<content:encoded><![CDATA[<p><a href="https://techsave-preview-com.3dcartstores.com/Game-Controller_p_13.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-controller1_thumbnail.jpg" align="right" border=0></a>controller is compatible with PC Windows (Xp/7/8/10) or later versions, Android 4.0 and PS3 via wired connection, working great with Laptop/PC, Android smart phones, TV boxes, tablets and PS3. This game controller can identify all the deices automati...<a href="https://techsave-preview-com.3dcartstores.com/Game-Controller_p_13.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $45.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=13&out=1" target="_new">Add to Cart</a>]</p><br clear=all>]]></content:encoded>
<isc:description><![CDATA[<span style="color: rgb(17, 17, 17); font-family: &quot;Amazon Ember&quot;, Arial, sans-serif; font-size: 13px; background-color: rgb(255, 255, 255);">controller is compatible with PC Windows (Xp/7/8/10) or later versions, Android 4.0 and PS3 via wired connection, working great with Laptop/PC, Android smart phones, TV boxes, tablets and PS3. This game controller can identify all the deices automatically, no need driver installation.</span>     ]]></isc:description>
<isc:productid><![CDATA[Game Controller]]></isc:productid>
<isc:thumb><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-controller1_thumbnail.jpg]]></isc:thumb>
<isc:image><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-controller1.jpg]]></isc:image>
<isc:price><![CDATA[$60.00]]></isc:price>
</item>
<item>
<title><![CDATA[Headphones]]></title>
<link>https://techsave-preview-com.3dcartstores.com/Headphones_p_14.html</link>
<pubDate>Sun, 16 Mar 2025 00:00:00 EST</pubDate>
<description><![CDATA[ <p><a href="https://techsave-preview-com.3dcartstores.com/Headphones_p_14.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-headphones1_thumbnail.jpg" align="right" border=0></a>Noise-rejecting dual-microphone system for clear phone calls and voice activation, which now includes Amazon Alexa. Simply update your software via the Bose Connect App and you will have the ability to hit the Action button to access hands-free voice...<a href="https://techsave-preview-com.3dcartstores.com/Headphones_p_14.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $275.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=14&out=1" target="_new">Add to Cart</a>]</p><br clear=all> ]]></description>
<guid isPermaLink="false">https://techsave-preview-com.3dcartstores.com/Headphones_p_14.html</guid>
<content:encoded><![CDATA[<p><a href="https://techsave-preview-com.3dcartstores.com/Headphones_p_14.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-headphones1_thumbnail.jpg" align="right" border=0></a>Noise-rejecting dual-microphone system for clear phone calls and voice activation, which now includes Amazon Alexa. Simply update your software via the Bose Connect App and you will have the ability to hit the Action button to access hands-free voice...<a href="https://techsave-preview-com.3dcartstores.com/Headphones_p_14.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $275.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=14&out=1" target="_new">Add to Cart</a>]</p><br clear=all>]]></content:encoded>
<isc:description><![CDATA[<ul class="a-unordered-list a-vertical a-spacing-none" style="box-sizing: border-box; margin: 0px 0px 0px 18px; color: rgb(148, 148, 148); padding: 0px; font-family: &quot;Amazon Ember&quot;, Arial, sans-serif; font-size: 13px; background-color: rgb(255, 255, 255);"><li style="box-sizing: border-box; list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: rgb(17, 17, 17);">Noise-rejecting dual-microphone system for clear phone calls and voice activation, which now includes Amazon Alexa. Simply update your software via the Bose Connect App and you will have the ability to hit the Action button to access hands-free voice control. You can also use the Action button to adjust the level of noise cancellation.</span></li><li style="box-sizing: border-box; list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: rgb(17, 17, 17);">Three levels of world-class noise cancellation for better listening experience in any environment</span></li><li style="box-sizing: border-box; list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: rgb(17, 17, 17);">Alexa-enabled for voice access to music, information and more</span></li></ul>   ]]></isc:description>
<isc:productid><![CDATA[Headphones]]></isc:productid>
<isc:thumb><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-headphones1_thumbnail.jpg]]></isc:thumb>
<isc:image><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-headphones1.jpg]]></isc:image>
<isc:price><![CDATA[$320.00]]></isc:price>
</item>
<item>
<title><![CDATA[23'' Laptop]]></title>
<link>https://techsave-preview-com.3dcartstores.com/23-Laptop_p_16.html</link>
<pubDate>Sun, 16 Mar 2025 00:00:00 EST</pubDate>
<description><![CDATA[ <p><a href="https://techsave-preview-com.3dcartstores.com/23-Laptop_p_16.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-laptop1_thumbnail.jpg" align="right" border=0></a>The new Aspire 3 Series is the perfect for every need. It packs a beautiful 23 HD screen, solid performance, and the latest WiFi into an attractive design that's easy to place in a backpack and take to class.7th Generation Intel Core i5-7200U Process...<a href="https://techsave-preview-com.3dcartstores.com/23-Laptop_p_16.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $290.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=16&out=1" target="_new">Add to Cart</a>]</p><br clear=all> ]]></description>
<guid isPermaLink="false">https://techsave-preview-com.3dcartstores.com/23-Laptop_p_16.html</guid>
<content:encoded><![CDATA[<p><a href="https://techsave-preview-com.3dcartstores.com/23-Laptop_p_16.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-laptop1_thumbnail.jpg" align="right" border=0></a>The new Aspire 3 Series is the perfect for every need. It packs a beautiful 23 HD screen, solid performance, and the latest WiFi into an attractive design that's easy to place in a backpack and take to class.7th Generation Intel Core i5-7200U Process...<a href="https://techsave-preview-com.3dcartstores.com/23-Laptop_p_16.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $290.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=16&out=1" target="_new">Add to Cart</a>]</p><br clear=all>]]></content:encoded>
<isc:description><![CDATA[<span style="font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">The new Aspire 3 Series is the perfect for every need. It packs a beautiful 23" HD screen, solid performance, and the latest WiFi into an attractive design that's easy to place in a backpack and take to class.</span><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">7th Generation Intel Core i5-7200U Processor (Up to 3.1GHz) <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">23" HD (1366 x 768) Widescreen LED-backlit Display <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">Intel HD Graphics 620 <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">6GB DDR4 Dual Channel Memory <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">1TB 5400RPM SATA Hard Drive <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">Windows 10 Home <span style="box-sizing: border-box; white-space: pre;"> </span></div><div style="box-sizing: border-box; font-family: BogleWeb, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px;">2-cell Li-Ion (4810 mAh) Battery, Up to 6.5 Hours Battery Life <span style="box-sizing: border-box; white-space: pre;"> </span></div>    ]]></isc:description>
<isc:productid><![CDATA[23'' Laptop]]></isc:productid>
<isc:thumb><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-laptop1_thumbnail.jpg]]></isc:thumb>
<isc:image><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-laptop1.jpg]]></isc:image>
<isc:price><![CDATA[$650.00]]></isc:price>
</item>
<item>
<title><![CDATA[D-Boss Game Controller]]></title>
<link>https://techsave-preview-com.3dcartstores.com/D-Boss-Game-Controller_p_17.html</link>
<pubDate>Sun, 16 Mar 2025 00:00:00 EST</pubDate>
<description><![CDATA[ <p><a href="https://techsave-preview-com.3dcartstores.com/D-Boss-Game-Controller_p_17.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-controller1_thumbnail.jpg" align="right" border=0></a>controller is compatible with PC Windows (Xp/7/8/10) or later versions, Android 4.0 and PS3 via wired connection, working great with Laptop/PC, Android smart phones, TV boxes, tablets and PS3. This game controller can identify all the deices automati...<a href="https://techsave-preview-com.3dcartstores.com/D-Boss-Game-Controller_p_17.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $45.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=17&out=1" target="_new">Add to Cart</a>]</p><br clear=all> ]]></description>
<guid isPermaLink="false">https://techsave-preview-com.3dcartstores.com/D-Boss-Game-Controller_p_17.html</guid>
<content:encoded><![CDATA[<p><a href="https://techsave-preview-com.3dcartstores.com/D-Boss-Game-Controller_p_17.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-controller1_thumbnail.jpg" align="right" border=0></a>controller is compatible with PC Windows (Xp/7/8/10) or later versions, Android 4.0 and PS3 via wired connection, working great with Laptop/PC, Android smart phones, TV boxes, tablets and PS3. This game controller can identify all the deices automati...<a href="https://techsave-preview-com.3dcartstores.com/D-Boss-Game-Controller_p_17.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $45.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=17&out=1" target="_new">Add to Cart</a>]</p><br clear=all>]]></content:encoded>
<isc:description><![CDATA[<span style="color: rgb(17, 17, 17); font-family: &quot;Amazon Ember&quot;, Arial, sans-serif; font-size: 13px; background-color: rgb(255, 255, 255);">controller is compatible with PC Windows (Xp/7/8/10) or later versions, Android 4.0 and PS3 via wired connection, working great with Laptop/PC, Android smart phones, TV boxes, tablets and PS3. This game controller can identify all the deices automatically, no need driver installation.</span>    ]]></isc:description>
<isc:productid><![CDATA[D-Boss Game Controller]]></isc:productid>
<isc:thumb><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-controller1_thumbnail.jpg]]></isc:thumb>
<isc:image><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-controller1.jpg]]></isc:image>
<isc:price><![CDATA[$55.00]]></isc:price>
</item>
<item>
<title><![CDATA[Wireless Headphones]]></title>
<link>https://techsave-preview-com.3dcartstores.com/Wireless-Headphones_p_18.html</link>
<pubDate>Sun, 16 Mar 2025 00:00:00 EST</pubDate>
<description><![CDATA[ <p><a href="https://techsave-preview-com.3dcartstores.com/Wireless-Headphones_p_18.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-headphones1_thumbnail.jpg" align="right" border=0></a>Noise-rejecting dual-microphone system for clear phone calls and voice activation, which now includes Amazon Alexa. Simply update your software via the Bose Connect App and you will have the ability to hit the Action button to access hands-free voice...<a href="https://techsave-preview-com.3dcartstores.com/Wireless-Headphones_p_18.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $275.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=18&out=1" target="_new">Add to Cart</a>]</p><br clear=all> ]]></description>
<guid isPermaLink="false">https://techsave-preview-com.3dcartstores.com/Wireless-Headphones_p_18.html</guid>
<content:encoded><![CDATA[<p><a href="https://techsave-preview-com.3dcartstores.com/Wireless-Headphones_p_18.html?referrer=rss"><img src="https://techsave-preview-com.3dcartstores.com/assets/images/item-headphones1_thumbnail.jpg" align="right" border=0></a>Noise-rejecting dual-microphone system for clear phone calls and voice activation, which now includes Amazon Alexa. Simply update your software via the Bose Connect App and you will have the ability to hit the Action button to access hands-free voice...<a href="https://techsave-preview-com.3dcartstores.com/Wireless-Headphones_p_18.html?referrer=rss">[Read More]</a><br><b>Our Price:</b> $275.00 <font color="red">On Sale</font> [<a href="https://techsave-preview-com.3dcartstores.com/add_cart.asp?quick=1&item_id=18&out=1" target="_new">Add to Cart</a>]</p><br clear=all>]]></content:encoded>
<isc:description><![CDATA[<ul class="a-unordered-list a-vertical a-spacing-none" style="box-sizing: border-box; margin: 0px 0px 0px 18px; color: rgb(148, 148, 148); padding: 0px; font-family: &quot;Amazon Ember&quot;, Arial, sans-serif; font-size: 13px; background-color: rgb(255, 255, 255);"><li style="box-sizing: border-box; list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: rgb(17, 17, 17);">Noise-rejecting dual-microphone system for clear phone calls and voice activation, which now includes Amazon Alexa. Simply update your software via the Bose Connect App and you will have the ability to hit the Action button to access hands-free voice control. You can also use the Action button to adjust the level of noise cancellation.</span></li><li style="box-sizing: border-box; list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: rgb(17, 17, 17);">Three levels of world-class noise cancellation for better listening experience in any environment</span></li><li style="box-sizing: border-box; list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box; color: rgb(17, 17, 17);">Alexa-enabled for voice access to music, information and more</span></li></ul>    ]]></isc:description>
<isc:productid><![CDATA[Wireless Headphones]]></isc:productid>
<isc:thumb><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-headphones1_thumbnail.jpg]]></isc:thumb>
<isc:image><![CDATA[https://techsave-preview-com.3dcartstores.com/assets/images/item-headphones1.jpg]]></isc:image>
<isc:price><![CDATA[$350.00]]></isc:price>
</item>
</channel></rss>